description: Ultralytics YOLO11n model trained on duplo-model-1/data.yaml
author: Ultralytics
date: '2025-04-12T13:48:47.178843'
version: 8.3.107
license: AGPL-3.0 License (https://ultralytics.com/license)
docs: https://docs.ultralytics.com
stride: 32
task: detect
batch: 1
imgsz:
- 640
- 640
names:
  0: '0'
args:
  batch: 1
  half: false
