description: Ultralytics YOLO11n model trained on duplos_4-2/data.yaml
author: Ultralytics
date: '2025-04-12T15:21:12.329498'
version: 8.3.107
license: AGPL-3.0 License (https://ultralytics.com/license)
docs: https://docs.ultralytics.com
stride: 32
task: detect
batch: 1
imgsz:
- 640
- 640
names:
  0: duplo detection augmented - v1 2023-06-01 8-48pm
args:
  batch: 1
  half: false
