name: Build and Publish image to Docker Hub
on:
  - workflow_dispatch

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build-image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t leshrimpkiller/vvv:latest --push .
